import click


def install(ctx: click.Context):
    """
    Install the wheel generated by the build command.

    Currently, only py3, non-abi, platform-independent wheels are supported.

    TODO: fully support PEP427 file naming.

    Args:
        ctx: The click context.

    Returns:

    """
    meta = get_project(ctx).meta
    module = f'{meta["name"]}-{meta["version"]}-py3-none-any.whl'
    cmd = ["pip", "install", "--upgrade", module]
    run(cmd)